blacklist: []
build_space: build_test
catkin_make_args: []
cmake_args: []
devel_layout: linked
devel_space: devel_test
extend_path: null
install: false
install_space: install_test
isolate_install: false
jobs_args: []
log_space: logs_test
make_args: []
source_space: src
use_env_cache: false
use_internal_make_jobserver: true
whitelist: []
